## Creating DataFrame

In [1]:
import pandas as pd
import numpy as np

In [3]:
price_data = [
    [100,200,400,600],
    [100,200,400,600],
    [100,200,400,600],
    [100,200,400,600],
]
list_df = pd.DataFrame(price_data)
type(list_df)

pandas.core.frame.DataFrame

In [2]:
price_data = {
    "Name": ["Apple", "Microsoft", "Tesla", "Meta"],
    "Open" : [100,200,400,600],
    "High":[100,200,400,600],
    "Low": [100,200,400,600],
    "Close":[100,200,400,600],
}
dict_df = pd.DataFrame(price_data)
dict_df.set_index("Name",inplace=True)

In [8]:
algo_df = pd.read_csv("../data/raw/algotrading_combined_dataset.csv")

In [7]:
funda_df = pd.read_csv("../data/raw/fundamental_research_dataset_large.csv")

In [9]:
algo_df.shape

(32870, 7)

In [10]:
funda_df.shape

(1050, 10)

In [13]:
algo_df.dtypes
funda_df.dtypes

Ticker                 object
Company Name           object
Sector                 object
Industry               object
Market Cap (B)        float64
EPS                   float64
P/E Ratio             float64
Dividend Yield (%)    float64
P/B Ratio             float64
D/E Ratio             float64
dtype: object

In [15]:
algo_df.index
funda_df.index

RangeIndex(start=0, stop=1050, step=1)

In [17]:
algo_df.columns
funda_df.columns

Index(['Ticker', 'Company Name', 'Sector', 'Industry', 'Market Cap (B)', 'EPS',
       'P/E Ratio', 'Dividend Yield (%)', 'P/B Ratio', 'D/E Ratio'],
      dtype='object')

In [18]:
algo_df.values

array([['2015-01-01', 'AAPL', 101.03184941004706, ..., 98.85235437937838,
        101.19741015525102, 344567.0],
       ['2015-01-02', 'AAPL', 100.8664959216968, ..., 99.5689811441504,
        101.22006444647305, 310521.0],
       ['2015-01-05', 'AAPL', 101.1644889006902, ..., 100.92012448620686,
        101.3398717110426, nan],
       ...,
       ['2018-03-09', 'AMZN', 98.07461328046368, ..., 96.20317673355092,
        97.48761554705614, 76911.0],
       ['2018-05-02', 'LTC/USD', 103.44322425714826, ...,
        103.1592860645143, nan, 552764.0],
       ['2020-09-18', 'ETH/USD', 164.75532933160764, ...,
        164.75532933160764, 164.72202588322403, 816832.0]],
      shape=(32870, 7), dtype=object)

In [19]:
algo_df.head()

         Date Ticker        Open        High         Low       Close    Volume
0  2015-01-01   AAPL  101.031849  101.329723   98.852354  101.197410  344567.0
1  2015-01-02   AAPL  100.866496  100.866496   99.568981  101.220064  310521.0
2  2015-01-05   AAPL  101.164489  101.176821  100.920124  101.339872       NaN
3  2015-01-06   AAPL         NaN  103.203859  102.287356  101.777905  295025.0
4  2015-01-07   AAPL  102.744728  104.050309  102.211701  102.090310  439080.0

In [20]:
funda_df.tail(20)

,Ticker,Company Name,Sector,Industry,Market Cap (B),EPS,P/E Ratio,Dividend Yield (%),P/B Ratio,D/E Ratio
1030,BRK.B,Berkshire Hathaway Inc.,Technology,Software,199.91,-0.17,14.67,9.07,14.35,0.85
1031,V,Visa Inc.,Technology,Semiconductors,233.24,0.61,38.93,7.79,12.89,2.82
1032,GOOGL,Alphabet Inc.,Healthcare,Biotechnology,262.81,9.31,5.19,8.19,6.76,1.95
1033,V,Visa Inc.,Consumer Goods,Beverages,145.61,8.56,8.95,4.59,NaN,2.70
1034,AAPL,Apple Inc.,Healthcare,Biotechnology,379.22,2.02,49.26,3.16,3.40,2.21
1035,JPM,JPMorgan Chase & Co.,Utilities,Water Utilities,166.41,-4.80,7.17,4.06,12.50,2.65
1036,JNJ,Johnson & Johnson,Utilities,Gas Utilities,129.87,-6.78,13.46,7.25,10.77,2.94
1037,TSLA,"Tesla, Inc.",Industrial Goods,Manufacturing,15.96,2.12,19.02,4.44,16.39,0.74
1038,GOOGL,Alphabet Inc.,Industrial Goods,Manufacturing,395.99,-4.35,17.99,8.64,NaN,0.70
1039,V,Visa Inc.,Consumer Goods,Food Products,341.65,3.11,30.00,2.93,12.46,1.23
1040,JPM,JPMorgan Chase & Co.,Healthcare,Medical Devices,443.02,7.27,25.33,4.98,6.11,2.99
1041,BRK.B,Berkshire Hathaway Inc.,Industrial Goods,Manufacturing,253.43,5.09,13.51,9.46,6.92,0.90
1042,MSFT,Microsoft Corporation,Technology,Software,22.24,5.64,22.14,0.96,11.40,0.84
1043,TSLA,"Tesla, Inc.",Healthcare,Pharmaceuticals,423.02,7.12,34.35,2.20,14.64,2.94
1044,V,Visa Inc.,Industrial Goods,Aerospace,251.18,NaN,8.75,5.30,4.37,1.02
1045,JNJ,Johnson & Johnson,Consumer Goods,Household Products,223.61,-3.54,5.61,7.97,6.63,1.07
1046,TSLA,"Tesla, Inc.",Industrial Goods,Construction,119.63,-1.20,18.18,NaN,8.04,0.08
1047,GOOGL,Alphabet Inc.,Utilities,Water Utilities,38.26,NaN,33.09,6.17,5.59,1.34
1048,V,Visa Inc.,Industrial Goods,Construction,117.11,-1.80,23.38,NaN,4.89,2.91
1049,JNJ,Johnson & Johnson,Technology,Semiconductors,376.25,7.39,49.40,3.35,7.18,0.69

In [21]:
algo_df.sample(30)

,Date,Ticker,Open,High,Low,Close,Volume
17302,2017-04-28,AUD/USD,95.082211,95.725594,95.066781,95.640353,338927.0
3846,2021-09-29,GOOG,190.668730,191.360091,190.668730,190.618999,731433.0
26772,2021-08-17,XRP/USD,186.238959,NaN,185.112391,186.604519,508619.0
2554,2016-10-17,GOOG,104.711131,105.954192,104.356621,105.656911,926193.0
26015,2018-09-21,XRP/USD,125.966912,127.076113,124.003525,125.519204,839628.0
27721,2017-04-06,LTC/USD,92.361032,NaN,91.545386,91.394455,464788.0
8424,2015-04-17,TSLA,91.464373,93.685501,91.464373,92.152296,616168.0
12654,2015-07-06,GBP/USD,87.667309,90.611261,86.723057,88.444862,427792.0
1929,2022-05-25,AAPL,179.582211,180.427300,179.028622,NaN,27965.0
26944,2022-04-14,XRP/USD,181.285289,182.759552,181.285289,182.933261,281153.0
18106,2020-05-28,AUD/USD,149.745379,151.343442,148.310433,150.493761,381457.0
13937,2020-06-04,GBP/USD,152.965879,153.286050,151.691225,152.675174,644913.0
406,2016-07-22,AAPL,105.406626,107.568110,105.406626,105.116350,111160.0
2284,2015-10-05,GOOG,92.327858,93.424283,92.317738,93.040836,434797.0
21373,2016-12-06,BTC/USD,104.931035,106.720649,104.931035,105.491814,586768.0
2753,2017-07-21,GOOG,94.427619,97.075659,93.384614,95.262491,244772.0
16741,2015-03-05,AUD/USD,89.724415,90.951522,88.189019,89.365547,61272.0
12602,2015-04-23,GBP/USD,89.033560,90.497509,NaN,88.907416,427903.0
1524,2020-11-04,AAPL,174.146957,174.678567,174.146957,173.678294,481588.0
22253,2020-04-21,BTC/USD,143.313186,145.699614,142.977717,143.465888,42446.0
3224,2019-05-13,GOOG,147.965899,149.387048,146.341635,147.769592,41693.0
6329,2015-04-07,AMZN,91.333387,91.857593,90.775046,90.916310,NaN
14671,2015-03-30,USD/JPY,NaN,89.949776,88.125635,89.690605,307081.0
1862,2022-02-21,AAPL,182.143530,183.942605,182.143530,182.903992,982555.0
22865,2022-08-25,BTC/USD,191.305783,193.517894,191.305783,192.665472,248663.0
28257,2019-04-26,LTC/USD,144.072756,145.461141,143.084710,143.560311,792290.0
31832,2021-06-07,AUD/USD,179.755044,181.132203,178.694390,179.785847,583061.0
32456,2021-07-14,EUR/USD,182.657945,183.351736,182.614699,182.971118,830017.0
2260,2015-09-01,GOOG,90.928477,91.993628,90.587104,90.618667,645161.0
4264,2015-05-07,MSFT,92.155026,92.838288,89.499245,92.080270,613242.0

In [22]:
algo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32870 entries, 0 to 32869
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    32870 non-null  object
 1   Ticker  32870 non-null  object
 2   Open    31495 non-null  float64
 3   High    31302 non-null  float64
 4   Low     31090 non-null  float64
 5   Close   30929 non-null  float64
 6   Volume  30802 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.8+ MB

In [23]:
algo_df.describe()

               Open          High           Low         Close         Volume
count  31495.000000  31302.000000  31090.000000  30929.000000   30802.000000
mean     133.600798    134.416157    132.420885    133.369927  492483.749302
std       35.566539     35.716248     35.661035     35.715660  283838.912786
min       83.254666     84.062713     81.978737     83.411785    1203.000000
25%       98.251137     98.928322     97.038250     97.824039  248663.000000
50%      132.147803    132.534488    130.718141    131.890827  490922.000000
75%      169.633748    171.193317    168.811891    170.103620  725434.000000
max      196.068319    196.712825    194.736434    196.349019  999653.000000

In [26]:
algo_df.isnull()
algo_df.isnull().sum()
funda_df.isnull().sum()

Ticker                  0
Company Name            0
Sector                  0
Industry                0
Market Cap (B)        104
EPS                   103
P/E Ratio             118
Dividend Yield (%)     99
P/B Ratio             116
D/E Ratio              97
dtype: int64

In [31]:
algo_df.duplicated()
algo_df.duplicated().sum()
funda_df.duplicated().sum()

np.int64(50)

In [ ]:
# rename column name
algo_df.rename(columns={'High': 'Max', 'Low': 'Min'})

,Date,Ticker,Open,Max,Min,Close,Volume
0,2015-01-01,AAPL,101.031849,101.329723,98.852354,101.197410,344567.0
1,2015-01-02,AAPL,100.866496,100.866496,99.568981,101.220064,310521.0
2,2015-01-05,AAPL,101.164489,101.176821,100.920124,101.339872,NaN
3,2015-01-06,AAPL,NaN,103.203859,102.287356,101.777905,295025.0
4,2015-01-07,AAPL,102.744728,104.050309,102.211701,102.090310,439080.0
...,...,...,...,...,...,...,...
32865,2021-08-02,AMZN,184.443237,185.375089,183.176491,183.087397,581356.0
32866,2017-01-24,AAPL,92.780364,93.092012,91.238510,NaN,754158.0
32867,2018-03-09,AMZN,98.074613,99.154029,96.203177,97.487616,76911.0
32868,2018-05-02,LTC/USD,103.443224,105.575739,103.159286,NaN,552764.0
32869,2020-09-18,ETH/USD,164.755329,166.936724,164.755329,164.722026,816832.0

## Maths Methods

In [36]:
algo_df.sum()
funda_df.sum()

Ticker                AAPLGOOGLMSFTAMZNTSLAFBBRK.BJNJJPMVAAPLGOOGLMS...
Company Name          Apple Inc.Alphabet Inc.Microsoft CorporationAm...
Sector                TechnologyFinanceFinanceHealthcareEnergyConsum...
Industry              SemiconductorsInvestment ServicesBanksPharmace...
Market Cap (B)                                                232554.06
EPS                                                              176.64
P/E Ratio                                                      25753.87
Dividend Yield (%)                                              4699.86
P/B Ratio                                                       9584.88
D/E Ratio                                                       1438.18
dtype: object

In [37]:
algo_df['High'].mean()

np.float64(134.41615698695395)

In [40]:
algo_df['High'].var()

np.float64(1275.6503714830637)

In [43]:
funda_df

,Ticker,Company Name,Sector,Industry,Market Cap (B),EPS,P/E Ratio,Dividend Yield (%),P/B Ratio,D/E Ratio
0,AAPL,Apple Inc.,Technology,Semiconductors,458.13,-9.78,44.16,2.19,9.17,2.56
1,GOOGL,Alphabet Inc.,Finance,Investment Services,215.85,4.86,27.56,8.14,14.93,0.06
2,MSFT,Microsoft Corporation,Finance,Banks,276.46,5.09,6.73,0.27,1.76,1.31
3,AMZN,"Amazon.com, Inc.",Healthcare,Pharmaceuticals,349.40,-0.53,28.30,5.92,15.40,0.27
4,TSLA,"Tesla, Inc.",Energy,Oil & Gas,248.55,9.92,27.04,2.20,10.20,0.12
...,...,...,...,...,...,...,...,...,...,...
1045,JNJ,Johnson & Johnson,Consumer Goods,Household Products,223.61,-3.54,5.61,7.97,6.63,1.07
1046,TSLA,"Tesla, Inc.",Industrial Goods,Construction,119.63,-1.20,18.18,NaN,8.04,0.08
1047,GOOGL,Alphabet Inc.,Utilities,Water Utilities,38.26,NaN,33.09,6.17,5.59,1.34
1048,V,Visa Inc.,Industrial Goods,Construction,117.11,-1.80,23.38,NaN,4.89,2.91
1049,JNJ,Johnson & Johnson,Technology,Semiconductors,376.25,7.39,49.40,3.35,7.18,0.69

## Select col from dataFrame

In [44]:
funda_df["Ticker"]
funda_df[["Ticker", "Sector"]]

     Ticker            Sector
0      AAPL        Technology
1     GOOGL           Finance
2      MSFT           Finance
3      AMZN        Healthcare
4      TSLA            Energy
...     ...               ...
1045    JNJ    Consumer Goods
1046   TSLA  Industrial Goods
1047  GOOGL         Utilities
1048      V  Industrial Goods
1049    JNJ        Technology

[1050 rows x 2 columns]

In [47]:
algo_df.iloc[0]
algo_df.iloc[0:4]
algo_df.iloc[0:4:2]

         Date Ticker        Open        High         Low       Close    Volume
0  2015-01-01   AAPL  101.031849  101.329723   98.852354  101.197410  344567.0
2  2015-01-05   AAPL  101.164489  101.176821  100.920124  101.339872       NaN

In [49]:
#Fancy Indexing
algo_df.iloc[[1,4,7,9,10,11]]

,Date,Ticker,Open,High,Low,Close,Volume
1,2015-01-02,AAPL,100.866496,100.866496,99.568981,101.220064,310521.0
4,2015-01-07,AAPL,102.744728,104.050309,102.211701,102.090310,439080.0
7,2015-01-12,AAPL,104.973922,105.968278,103.491534,104.203536,779883.0
9,2015-01-14,AAPL,104.211973,104.931374,104.088945,103.762217,427009.0
10,2015-01-15,AAPL,104.830035,104.830035,102.731556,104.636914,557718.0
11,2015-01-16,AAPL,NaN,103.846070,102.675870,103.813307,703922.0

In [55]:
algo_df

,Date,Ticker,Open,High,Low,Close,Volume
0,2015-01-01,AAPL,101.031849,101.329723,98.852354,101.197410,344567.0
1,2015-01-02,AAPL,100.866496,100.866496,99.568981,101.220064,310521.0
2,2015-01-05,AAPL,101.164489,101.176821,100.920124,101.339872,NaN
3,2015-01-06,AAPL,NaN,103.203859,102.287356,101.777905,295025.0
4,2015-01-07,AAPL,102.744728,104.050309,102.211701,102.090310,439080.0
...,...,...,...,...,...,...,...
32865,2021-08-02,AMZN,184.443237,185.375089,183.176491,183.087397,581356.0
32866,2017-01-24,AAPL,92.780364,93.092012,91.238510,NaN,754158.0
32867,2018-03-09,AMZN,98.074613,99.154029,96.203177,97.487616,76911.0
32868,2018-05-02,LTC/USD,103.443224,105.575739,103.159286,NaN,552764.0
32869,2020-09-18,ETH/USD,164.755329,166.936724,164.755329,164.722026,816832.0

In [ ]:
funda_df.loc[["AAPL","AMZN" ]]

KeyError: "None of [Index(['AAPL', 'AMZN'], dtype='object')] are in the [index]"

In [60]:
funda_df.iloc[0:10]
funda_df.iloc[0:10:2]

,Ticker,Company Name,Sector,Industry,Market Cap (B),EPS,P/E Ratio,Dividend Yield (%),P/B Ratio,D/E Ratio
0,AAPL,Apple Inc.,Technology,Semiconductors,458.13,-9.78,44.16,2.19,9.17,2.56
2,MSFT,Microsoft Corporation,Finance,Banks,276.46,5.09,6.73,0.27,1.76,1.31
4,TSLA,"Tesla, Inc.",Energy,Oil & Gas,248.55,9.92,27.04,2.20,10.20,0.12
6,BRK.B,Berkshire Hathaway Inc.,Technology,Hardware,NaN,-4.01,NaN,6.92,8.03,0.08
8,JPM,JPMorgan Chase & Co.,Finance,Banks,260.95,0.21,21.25,7.18,12.03,1.52

In [61]:
funda_df.iloc[0:5,0:4]

  Ticker           Company Name      Sector             Industry
0   AAPL             Apple Inc.  Technology       Semiconductors
1  GOOGL          Alphabet Inc.     Finance  Investment Services
2   MSFT  Microsoft Corporation     Finance                Banks
3   AMZN       Amazon.com, Inc.  Healthcare      Pharmaceuticals
4   TSLA            Tesla, Inc.      Energy            Oil & Gas

In [62]:
funda_df

,Ticker,Company Name,Sector,Industry,Market Cap (B),EPS,P/E Ratio,Dividend Yield (%),P/B Ratio,D/E Ratio
0,AAPL,Apple Inc.,Technology,Semiconductors,458.13,-9.78,44.16,2.19,9.17,2.56
1,GOOGL,Alphabet Inc.,Finance,Investment Services,215.85,4.86,27.56,8.14,14.93,0.06
2,MSFT,Microsoft Corporation,Finance,Banks,276.46,5.09,6.73,0.27,1.76,1.31
3,AMZN,"Amazon.com, Inc.",Healthcare,Pharmaceuticals,349.40,-0.53,28.30,5.92,15.40,0.27
4,TSLA,"Tesla, Inc.",Energy,Oil & Gas,248.55,9.92,27.04,2.20,10.20,0.12
...,...,...,...,...,...,...,...,...,...,...
1045,JNJ,Johnson & Johnson,Consumer Goods,Household Products,223.61,-3.54,5.61,7.97,6.63,1.07
1046,TSLA,"Tesla, Inc.",Industrial Goods,Construction,119.63,-1.20,18.18,NaN,8.04,0.08
1047,GOOGL,Alphabet Inc.,Utilities,Water Utilities,38.26,NaN,33.09,6.17,5.59,1.34
1048,V,Visa Inc.,Industrial Goods,Construction,117.11,-1.80,23.38,NaN,4.89,2.91
1049,JNJ,Johnson & Johnson,Technology,Semiconductors,376.25,7.39,49.40,3.35,7.18,0.69

In [69]:
funda_df.loc[0:4,"Company Name": "Market Cap (B)"]

            Company Name      Sector             Industry  Market Cap (B)
0             Apple Inc.  Technology       Semiconductors          458.13
1          Alphabet Inc.     Finance  Investment Services          215.85
2  Microsoft Corporation     Finance                Banks          276.46
3       Amazon.com, Inc.  Healthcare      Pharmaceuticals          349.40
4            Tesla, Inc.      Energy            Oil & Gas          248.55

In [67]:
algo_df.loc[0:4,"Date":"Close"]

         Date Ticker        Open        High         Low       Close
0  2015-01-01   AAPL  101.031849  101.329723   98.852354  101.197410
1  2015-01-02   AAPL  100.866496  100.866496   99.568981  101.220064
2  2015-01-05   AAPL  101.164489  101.176821  100.920124  101.339872
3  2015-01-06   AAPL         NaN  103.203859  102.287356  101.777905
4  2015-01-07   AAPL  102.744728  104.050309  102.211701  102.090310

In [70]:
algo_df["New Col"] = "Sumit"

In [71]:
algo_df

,Date,Ticker,Open,High,Low,Close,Volume,New Col
0,2015-01-01,AAPL,101.031849,101.329723,98.852354,101.197410,344567.0,Sumit
1,2015-01-02,AAPL,100.866496,100.866496,99.568981,101.220064,310521.0,Sumit
2,2015-01-05,AAPL,101.164489,101.176821,100.920124,101.339872,NaN,Sumit
3,2015-01-06,AAPL,NaN,103.203859,102.287356,101.777905,295025.0,Sumit
4,2015-01-07,AAPL,102.744728,104.050309,102.211701,102.090310,439080.0,Sumit
...,...,...,...,...,...,...,...,...
32865,2021-08-02,AMZN,184.443237,185.375089,183.176491,183.087397,581356.0,Sumit
32866,2017-01-24,AAPL,92.780364,93.092012,91.238510,NaN,754158.0,Sumit
32867,2018-03-09,AMZN,98.074613,99.154029,96.203177,97.487616,76911.0,Sumit
32868,2018-05-02,LTC/USD,103.443224,105.575739,103.159286,NaN,552764.0,Sumit
32869,2020-09-18,ETH/USD,164.755329,166.936724,164.755329,164.722026,816832.0,Sumit

In [72]:
algo_df["New Close"] = algo_df["Close"] * 100

In [73]:
algo_df

,Date,Ticker,Open,High,Low,Close,Volume,New Col,New Close
0,2015-01-01,AAPL,101.031849,101.329723,98.852354,101.197410,344567.0,Sumit,10119.741016
1,2015-01-02,AAPL,100.866496,100.866496,99.568981,101.220064,310521.0,Sumit,10122.006445
2,2015-01-05,AAPL,101.164489,101.176821,100.920124,101.339872,NaN,Sumit,10133.987171
3,2015-01-06,AAPL,NaN,103.203859,102.287356,101.777905,295025.0,Sumit,10177.790504
4,2015-01-07,AAPL,102.744728,104.050309,102.211701,102.090310,439080.0,Sumit,10209.031003
...,...,...,...,...,...,...,...,...,...
32865,2021-08-02,AMZN,184.443237,185.375089,183.176491,183.087397,581356.0,Sumit,18308.739709
32866,2017-01-24,AAPL,92.780364,93.092012,91.238510,NaN,754158.0,Sumit,NaN
32867,2018-03-09,AMZN,98.074613,99.154029,96.203177,97.487616,76911.0,Sumit,9748.761555
32868,2018-05-02,LTC/USD,103.443224,105.575739,103.159286,NaN,552764.0,Sumit,NaN
32869,2020-09-18,ETH/USD,164.755329,166.936724,164.755329,164.722026,816832.0,Sumit,16472.202588