## Pandas

In [1]:
import pandas as pd
import numpy as np

## Series

In [3]:
list_str = ["Apple","Microsoft","Ethereum"]
pd.Series(list_str)

0        Apple
1    Microsoft
2     Ethereum
dtype: object

In [5]:
list_int = [100,101,102,103]
pd.Series(list_int)

0    100
1    101
2    102
3    103
dtype: int64

In [12]:
list_int = [100,101,102,103]
list_str = ["Apple","Microsoft","Ethereum", "Nvidia"]
ser_cust = pd.Series(list_int,index=list_str)
type(ser_cust)

pandas.core.series.Series

In [11]:
ser_cust["Apple"]
ser_cust[0]

C:\Users\dell\AppData\Local\Temp\ipykernel_11424\4130743153.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_cust[0]

np.int64(100)

In [14]:
list_int = [100,101,102,103]
list_str = ["Apple","Microsoft","Ethereum", "Nvidia"]
pd.Series(list_int,index=list_str,name="The Stock Prices of Sumit")

Apple        100
Microsoft    101
Ethereum     102
Nvidia       103
Name: The Stock Prices of Sumit, dtype: int64

## Series from dict

In [32]:
dict_ser  = {"Apple": 100, "Microsoft":200,"Bitcoin":300000,"Etherum":400}
dict_ser
dict_ser=pd.Series(dict_ser,name="The Stock prices of Sumit")
type(dict_ser)

pandas.core.series.Series

## Series Attributes

In [36]:
dict_ser.dtype
dict_ser.size
dict_ser.name
dict_ser.is_unique
dict_ser.index
dict_ser.values
type(dict_ser.values)

numpy.ndarray

## Series using read_csv

In [37]:
# with one col

import requests
import pandas as pd

# Define the API endpoint
url = "https://api.coingecko.com/api/v3/coins/markets"

# Define the parameters for the API request
params = {
    "vs_currency": "usd",
    "order": "market_cap_desc",
    "per_page": 100,
    "page": 1,
    "sparkline": False
}

# Make the API request
response = requests.get(url, params=params)

# Check if the request was successful
if response.status_code == 200:
    # Parse the JSON data
    data = response.json()

    # Create a DataFrame from the data
    df = pd.DataFrame(data)

    # Display the DataFrame
    print(df.head())
else:
    print(f"Failed to fetch data: {response.status_code}")

            id symbol      name  \
0      bitcoin    btc   Bitcoin
1     ethereum    eth  Ethereum
2       tether   usdt    Tether
3  binancecoin    bnb       BNB
4     usd-coin   usdc      USDC

                                               image  current_price  \
0  https://coin-images.coingecko.com/coins/images...   64104.000000
1  https://coin-images.coingecko.com/coins/images...    1726.180000
2  https://coin-images.coingecko.com/coins/images...       0.998892
3  https://coin-images.coingecko.com/coins/images...     589.850000
4  https://coin-images.coingecko.com/coins/images...       0.999878

      market_cap  market_cap_rank  fully_diluted_valuation  total_volume  \
0  1285121763243                1            1285121763243  1.397490e+10
1   208359927407                2             208359927407  8.944073e+09
2   186220413890                3             191681014110  2.925259e+10
3    79534689076                4              79534689076  4.298064e+08
4    74805611644                5              74806477592  5.257518e+09

       high_24h  ...  total_supply   max_supply         ath  \
0  64462.000000  ...  2.004598e+07   21000000.0  126080.000
1   1742.080000  ...  1.206839e+08          NaN    4946.050
2      0.998999  ...  1.919036e+11          NaN       1.320
3    590.820000  ...  1.347834e+08  200000000.0    1369.990
4      1.000000  ...  7.481844e+10          NaN       1.043

   ath_change_percentage                  ath_date        atl  \
0              -49.15587  2025-10-06T18:57:42.558Z  67.810000
1              -65.09980  2025-08-24T19:21:03.333Z   0.432979
2              -24.50613  2018-07-24T00:00:00.000Z   0.572521
3              -56.94465  2025-10-13T08:41:24.131Z   0.039818
4               -4.17690  2018-11-15T00:00:00.000Z   0.877647

   atl_change_percentage                  atl_date  \
0           9.443645e+04  2013-07-06T00:00:00.000Z
1           3.985755e+05  2015-10-20T00:00:00.000Z
2           7.446624e+01  2015-03-02T00:00:00.000Z
3           1.481288e+06  2017-10-19T00:00:00.000Z
4           1.392742e+01  2023-03-11T08:02:13.981Z

                                                 roi              last_updated
0                                               None  2026-06-21T17:21:12.417Z
1  {'times': 35.004333884066355, 'currency': 'btc...  2026-06-21T17:21:12.783Z
2                                               None  2026-06-21T17:21:12.626Z
3                                               None  2026-06-21T17:21:11.594Z
4                                               None  2026-06-21T17:21:11.780Z

[5 rows x 26 columns]

In [38]:
df

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,64104.000000,1285121763243,1,1285121763243,1.397490e+10,64462.000000,...,2.004598e+07,2.100000e+07,126080.000000,-49.15587,2025-10-06T18:57:42.558Z,67.810000,9.443645e+04,2013-07-06T00:00:00.000Z,None,2026-06-21T17:21:12.417Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1726.180000,208359927407,2,208359927407,8.944073e+09,1742.080000,...,1.206839e+08,NaN,4946.050000,-65.09980,2025-08-24T19:21:03.333Z,0.432979,3.985755e+05,2015-10-20T00:00:00.000Z,"{'times': 35.004333884066355, 'currency': 'btc...",2026-06-21T17:21:12.783Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.998892,186220413890,3,191681014110,2.925259e+10,0.998999,...,1.919036e+11,NaN,1.320000,-24.50613,2018-07-24T00:00:00.000Z,0.572521,7.446624e+01,2015-03-02T00:00:00.000Z,None,2026-06-21T17:21:12.626Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,589.850000,79534689076,4,79534689076,4.298064e+08,590.820000,...,1.347834e+08,2.000000e+08,1369.990000,-56.94465,2025-10-13T08:41:24.131Z,0.039818,1.481288e+06,2017-10-19T00:00:00.000Z,None,2026-06-21T17:21:11.594Z
4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999878,74805611644,5,74806477592,5.257518e+09,1.000000,...,7.481844e+10,NaN,1.043000,-4.17690,2018-11-15T00:00:00.000Z,0.877647,1.392742e+01,2023-03-11T08:02:13.981Z,None,2026-06-21T17:21:11.780Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,aptos,apt,Aptos,https://coin-images.coingecko.com/coins/images...,0.657939,547558215,96,792577245,3.613270e+07,0.664210,...,1.204526e+09,2.100000e+09,19.920000,-96.70391,2023-01-26T14:25:17.390Z,0.609733,7.687050e+00,2026-06-10T22:10:23.967Z,None,2026-06-21T17:21:12.098Z
96,midnight-3,night,Midnight,https://coin-images.coingecko.com/coins/images...,0.032902,546102960,97,789194667,9.884282e+06,0.033193,...,2.400000e+10,2.400000e+10,0.118529,-72.27729,2025-12-09T09:29:38.386Z,0.023780,3.817918e+01,2025-12-09T09:48:36.670Z,None,2026-06-21T17:20:49.356Z
97,arbitrum,arb,Arbitrum,https://coin-images.coingecko.com/coins/images...,0.084027,535310644,98,841307586,2.485366e+07,0.084812,...,1.000000e+10,1.000000e+10,2.390000,-96.48834,2024-01-12T12:29:59.231Z,0.074613,1.249810e+01,2026-06-06T05:05:27.312Z,None,2026-06-21T17:21:09.980Z
98,pump-fun,pump,Pump.fun,https://coin-images.coingecko.com/coins/images...,0.001531,527600402,99,1305456029,6.153289e+07,0.001529,...,8.566955e+11,1.000000e+12,0.008819,-82.64265,2025-09-14T16:42:40.248Z,0.001316,1.628324e+01,2026-06-06T04:36:07.693Z,None,2026-06-21T17:20:48.770Z
99,adi-token,adi,ADI,https://coin-images.coingecko.com/coins/images...,4.140000,518952392,100,4140628607,5.622569e+06,4.160000,...,1.000000e+09,1.000000e+09,4.550000,-8.87408,2026-04-03T21:30:15.912Z,0.975425,3.247693e+02,2025-12-10T09:46:25.812Z,None,2026-06-21T17:20:49.092Z

In [44]:
df.to_csv("Day_23_AlgoTrading.csv")

In [55]:
df = pd.read_csv("Day_23_AlgoTrading.csv")
df

,Unnamed: 0.1,Unnamed: 0,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,0,0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,64104.000000,1285121763243,1,1285121763243,...,2.004598e+07,2.100000e+07,126080.000000,-49.15587,2025-10-06T18:57:42.558Z,67.810000,9.443645e+04,2013-07-06T00:00:00.000Z,NaN,2026-06-21T17:21:12.417Z
1,1,1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,1726.180000,208359927407,2,208359927407,...,1.206839e+08,NaN,4946.050000,-65.09980,2025-08-24T19:21:03.333Z,0.432979,3.985755e+05,2015-10-20T00:00:00.000Z,"{'times': 35.004333884066355, 'currency': 'btc...",2026-06-21T17:21:12.783Z
2,2,2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.998892,186220413890,3,191681014110,...,1.919036e+11,NaN,1.320000,-24.50613,2018-07-24T00:00:00.000Z,0.572521,7.446624e+01,2015-03-02T00:00:00.000Z,NaN,2026-06-21T17:21:12.626Z
3,3,3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,589.850000,79534689076,4,79534689076,...,1.347834e+08,2.000000e+08,1369.990000,-56.94465,2025-10-13T08:41:24.131Z,0.039818,1.481288e+06,2017-10-19T00:00:00.000Z,NaN,2026-06-21T17:21:11.594Z
4,4,4,usd-coin,usdc,USDC,https://coin-images.coingecko.com/coins/images...,0.999878,74805611644,5,74806477592,...,7.481844e+10,NaN,1.043000,-4.17690,2018-11-15T00:00:00.000Z,0.877647,1.392742e+01,2023-03-11T08:02:13.981Z,NaN,2026-06-21T17:21:11.780Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,95,aptos,apt,Aptos,https://coin-images.coingecko.com/coins/images...,0.657939,547558215,96,792577245,...,1.204526e+09,2.100000e+09,19.920000,-96.70391,2023-01-26T14:25:17.390Z,0.609733,7.687050e+00,2026-06-10T22:10:23.967Z,NaN,2026-06-21T17:21:12.098Z
96,96,96,midnight-3,night,Midnight,https://coin-images.coingecko.com/coins/images...,0.032902,546102960,97,789194667,...,2.400000e+10,2.400000e+10,0.118529,-72.27729,2025-12-09T09:29:38.386Z,0.023780,3.817918e+01,2025-12-09T09:48:36.670Z,NaN,2026-06-21T17:20:49.356Z
97,97,97,arbitrum,arb,Arbitrum,https://coin-images.coingecko.com/coins/images...,0.084027,535310644,98,841307586,...,1.000000e+10,1.000000e+10,2.390000,-96.48834,2024-01-12T12:29:59.231Z,0.074613,1.249810e+01,2026-06-06T05:05:27.312Z,NaN,2026-06-21T17:21:09.980Z
98,98,98,pump-fun,pump,Pump.fun,https://coin-images.coingecko.com/coins/images...,0.001531,527600402,99,1305456029,...,8.566955e+11,1.000000e+12,0.008819,-82.64265,2025-09-14T16:42:40.248Z,0.001316,1.628324e+01,2026-06-06T04:36:07.693Z,NaN,2026-06-21T17:20:48.770Z
99,99,99,adi-token,adi,ADI,https://coin-images.coingecko.com/coins/images...,4.140000,518952392,100,4140628607,...,1.000000e+09,1.000000e+09,4.550000,-8.87408,2026-04-03T21:30:15.912Z,0.975425,3.247693e+02,2025-12-10T09:46:25.812Z,NaN,2026-06-21T17:20:49.092Z

In [56]:
df  = df[["name","current_price"]]

In [57]:
df

        name  current_price
0    Bitcoin   64104.000000
1   Ethereum    1726.180000
2     Tether       0.998892
3        BNB     589.850000
4       USDC       0.999878
..       ...            ...
95     Aptos       0.657939
96  Midnight       0.032902
97  Arbitrum       0.084027
98  Pump.fun       0.001531
99       ADI       4.140000

[100 rows x 2 columns]

In [49]:
type(df[["name","current_price"]])

pandas.core.frame.DataFrame

In [69]:
# convert data frame to series
ser = df.squeeze()
ser

name
Bitcoin     64104.000000
Ethereum     1726.180000
Tether          0.998892
BNB           589.850000
USDC            0.999878
                ...
Aptos           0.657939
Midnight        0.032902
Arbitrum        0.084027
Pump.fun        0.001531
ADI             4.140000
Name: current_price, Length: 100, dtype: float64

In [61]:
type(ser)

pandas.core.series.Series

In [59]:
df  = df.set_index("name")
df

KeyError: "None of ['name'] are in the columns"

In [65]:
ser

name
Bitcoin     64104.000000
Ethereum     1726.180000
Tether          0.998892
BNB           589.850000
USDC            0.999878
                ...
Aptos           0.657939
Midnight        0.032902
Arbitrum        0.084027
Pump.fun        0.001531
ADI             4.140000
Name: current_price, Length: 100, dtype: float64

In [66]:
import sys
sys.getsizeof(ser)

11769

In [68]:
#change data type
aser = ser.astype(np.float32)
sys.getsizeof(aser)

11369