### Multiindex

In [44]:
import pandas as pd
import numpy as np
import yfinance as yf

In [45]:
tickers = ['AAPL','AMZN','META','MSFT']
start  ='2026-01-01'
end  ='2026-06-01'
           
def fetch_data(tickers, start, end):
    data = yf.download(tickers,start,end)
    return data
df = fetch_data(tickers,start,end)

[*********************100%***********************]  3 of 4 completed

In [46]:
df

Price            Close                                            High  \
Ticker            AAPL        AMZN        META        MSFT        AAPL
Date
2026-01-02  270.507416  226.500000  649.251831  470.843201  277.324736
2026-01-05  266.764374  233.059998  657.616943  470.753632  271.006492
2026-01-06  261.873444  240.929993  659.443665  476.388519  267.053821
2026-01-07  259.847198  241.559998  647.534912  481.326508  263.190992
2026-01-08  258.559631  246.289993  644.909607  475.990265  258.809168
...                ...         ...         ...         ...         ...
2026-05-22  308.820007  266.320007  609.694946  418.570007  311.399994
2026-05-26  308.329987  265.290009  611.773010  416.029999  311.820007
2026-05-27  310.850006  271.850006  634.671814  412.670013  313.260010
2026-05-28  312.510010  274.000000  634.701721  426.989990  312.799988
2026-05-29  312.059998  270.640015  631.924316  450.239990  315.000000

Price                                                  Low              \
Ticker            AMZN        META        MSFT        AAPL        AMZN
Date
2026-01-02  235.460007  663.206979  482.511241  268.501134  224.699997
2026-01-05  234.000000  663.356705  473.959357  265.646456  227.179993
2026-01-06  243.179993  664.334964  476.617480  261.633898  232.070007
2026-01-07  245.289993  657.976308  487.528897  259.328174  239.520004
2026-01-08  246.410004  645.947733  480.520111  255.225814  241.880005
...                ...         ...         ...         ...         ...
2026-05-22  269.790009  614.240721  424.399994  305.839996  266.239990
2026-05-26  269.299988  613.900982  419.769989  307.670013  262.070007
2026-05-27  272.410004  637.908804  415.940002  308.299988  265.700012
2026-05-28  274.500000  642.404604  429.489990  309.570007  267.440002
2026-05-29  274.750000  633.912464  450.329987  309.529999  269.640015

Price                                     Open                          \
Ticker            META        MSFT        AAPL        AMZN        META
Date
2026-01-02  642.354162  468.075527  271.755098  231.339996  661.549901
2026-01-05  646.596623  467.418478  270.138110  228.839996  649.850828
2026-01-06  650.739221  467.667347  266.504853  232.100006  658.395546
2026-01-07  643.661816  475.830992  262.711902  239.610001  654.472549
2026-01-08  634.587992  473.750240  256.543358  243.059998  644.729935
...                ...         ...         ...         ...         ...
2026-05-22  606.388014  416.329987  306.119995  268.660004  607.317145
2026-05-26  604.739490  413.019989  309.559998  267.940002  608.326193
2026-05-27  608.436119  409.579987  308.329987  266.149994  608.835773
2026-05-28  628.727278  412.670013  310.679993  272.269989  638.907845
2026-05-29  622.772764  432.359985  311.779999  271.290009  632.913390

Price                     Volume
Ticker            MSFT      AAPL      AMZN      META      MSFT
Date
2026-01-02  482.242449  37838100  51456200  13726500  25571600
2026-01-05  471.958259  45647200  49733300  12213700  25250300
2026-01-06  471.699379  52352100  53764700  11074400  23037700
2026-01-07  477.632965  48309800  42236500  12846300  25564200
2026-01-08  479.106393  50419300  39509800  11921700  18162600
...                ...       ...       ...       ...       ...
2026-05-22  419.540009  43670200  27535500  11688600  22390300
2026-05-26  416.429993  48000500  38028100  12234200  30398000
2026-05-27  411.010010  50430900  40061900  23143600  28901500
2026-05-28  412.980011  48220400  40630400  16772400  47250500
2026-05-29  432.549988  70026800  54749600  19806500  79654400

[102 rows x 20 columns]

In [47]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 102 entries, 2026-01-02 to 2026-05-29
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, AAPL)   102 non-null    float64
 1   (Close, AMZN)   102 non-null    float64
 2   (Close, META)   102 non-null    float64
 3   (Close, MSFT)   102 non-null    float64
 4   (High, AAPL)    102 non-null    float64
 5   (High, AMZN)    102 non-null    float64
 6   (High, META)    102 non-null    float64
 7   (High, MSFT)    102 non-null    float64
 8   (Low, AAPL)     102 non-null    float64
 9   (Low, AMZN)     102 non-null    float64
 10  (Low, META)     102 non-null    float64
 11  (Low, MSFT)     102 non-null    float64
 12  (Open, AAPL)    102 non-null    float64
 13  (Open, AMZN)    102 non-null    float64
 14  (Open, META)    102 non-null    float64
 15  (Open, MSFT)    102 non-null    float64
 16  (Volume, AAPL)  102 non-null    int64
 17  (Volume, AMZN)  102 non-null    int64
 18  (Volume, META)  102 non-null    int64
 19  (Volume, MSFT)  102 non-null    int64
dtypes: float64(16), int64(4)
memory usage: 16.7 KB

In [48]:
type(df)

pandas.DataFrame

In [49]:
# check index on columns
df.index

DatetimeIndex(['2026-01-02', '2026-01-05', '2026-01-06', '2026-01-07',
               '2026-01-08', '2026-01-09', '2026-01-12', '2026-01-13',
               '2026-01-14', '2026-01-15',
               ...
               '2026-05-15', '2026-05-18', '2026-05-19', '2026-05-20',
               '2026-05-21', '2026-05-22', '2026-05-26', '2026-05-27',
               '2026-05-28', '2026-05-29'],
              dtype='datetime64[s]', name='Date', length=102, freq=None)

In [50]:
df

Price            Close                                            High  \
Ticker            AAPL        AMZN        META        MSFT        AAPL
Date
2026-01-02  270.507416  226.500000  649.251831  470.843201  277.324736
2026-01-05  266.764374  233.059998  657.616943  470.753632  271.006492
2026-01-06  261.873444  240.929993  659.443665  476.388519  267.053821
2026-01-07  259.847198  241.559998  647.534912  481.326508  263.190992
2026-01-08  258.559631  246.289993  644.909607  475.990265  258.809168
...                ...         ...         ...         ...         ...
2026-05-22  308.820007  266.320007  609.694946  418.570007  311.399994
2026-05-26  308.329987  265.290009  611.773010  416.029999  311.820007
2026-05-27  310.850006  271.850006  634.671814  412.670013  313.260010
2026-05-28  312.510010  274.000000  634.701721  426.989990  312.799988
2026-05-29  312.059998  270.640015  631.924316  450.239990  315.000000

Price                                                  Low              \
Ticker            AMZN        META        MSFT        AAPL        AMZN
Date
2026-01-02  235.460007  663.206979  482.511241  268.501134  224.699997
2026-01-05  234.000000  663.356705  473.959357  265.646456  227.179993
2026-01-06  243.179993  664.334964  476.617480  261.633898  232.070007
2026-01-07  245.289993  657.976308  487.528897  259.328174  239.520004
2026-01-08  246.410004  645.947733  480.520111  255.225814  241.880005
...                ...         ...         ...         ...         ...
2026-05-22  269.790009  614.240721  424.399994  305.839996  266.239990
2026-05-26  269.299988  613.900982  419.769989  307.670013  262.070007
2026-05-27  272.410004  637.908804  415.940002  308.299988  265.700012
2026-05-28  274.500000  642.404604  429.489990  309.570007  267.440002
2026-05-29  274.750000  633.912464  450.329987  309.529999  269.640015

Price                                     Open                          \
Ticker            META        MSFT        AAPL        AMZN        META
Date
2026-01-02  642.354162  468.075527  271.755098  231.339996  661.549901
2026-01-05  646.596623  467.418478  270.138110  228.839996  649.850828
2026-01-06  650.739221  467.667347  266.504853  232.100006  658.395546
2026-01-07  643.661816  475.830992  262.711902  239.610001  654.472549
2026-01-08  634.587992  473.750240  256.543358  243.059998  644.729935
...                ...         ...         ...         ...         ...
2026-05-22  606.388014  416.329987  306.119995  268.660004  607.317145
2026-05-26  604.739490  413.019989  309.559998  267.940002  608.326193
2026-05-27  608.436119  409.579987  308.329987  266.149994  608.835773
2026-05-28  628.727278  412.670013  310.679993  272.269989  638.907845
2026-05-29  622.772764  432.359985  311.779999  271.290009  632.913390

Price                     Volume
Ticker            MSFT      AAPL      AMZN      META      MSFT
Date
2026-01-02  482.242449  37838100  51456200  13726500  25571600
2026-01-05  471.958259  45647200  49733300  12213700  25250300
2026-01-06  471.699379  52352100  53764700  11074400  23037700
2026-01-07  477.632965  48309800  42236500  12846300  25564200
2026-01-08  479.106393  50419300  39509800  11921700  18162600
...                ...       ...       ...       ...       ...
2026-05-22  419.540009  43670200  27535500  11688600  22390300
2026-05-26  416.429993  48000500  38028100  12234200  30398000
2026-05-27  411.010010  50430900  40061900  23143600  28901500
2026-05-28  412.980011  48220400  40630400  16772400  47250500
2026-05-29  432.549988  70026800  54749600  19806500  79654400

[102 rows x 20 columns]

In [51]:
df.columns

MultiIndex([( 'Close', 'AAPL'),
            ( 'Close', 'AMZN'),
            ( 'Close', 'META'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High', 'AMZN'),
            (  'High', 'META'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low', 'AMZN'),
            (   'Low', 'META'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open', 'AMZN'),
            (  'Open', 'META'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume', 'AMZN'),
            ('Volume', 'META'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])

In [52]:
# can we have Multi index?
pd.Series([1,2,3,4,5])
type(pd.DataFrame([1,2,3,4,5]))

pandas.DataFrame

In [53]:
ser = pd.Series([1,2,3,4,5])
df = pd.DataFrame([1,2,3,4,5])

In [54]:
m_index = [("AAPL",1),("MSFT",2),("META",3),("TCS",4),("IOCL",5)]
m_ser = pd.Series([100,200,300,400,500],index=m_index)
m_df = pd.DataFrame([100,200,300,400,500],index=m_index)
print(m_ser)
print(m_df)

(AAPL, 1)    100
(MSFT, 2)    200
(META, 3)    300
(TCS, 4)     400
(IOCL, 5)    500
dtype: int64
             0
(AAPL, 1)  100
(MSFT, 2)  200
(META, 3)  300
(TCS, 4)   400
(IOCL, 5)  500

In [55]:
m_ser[('AAPL', 1)]

np.int64(100)

In [56]:
m_df.index

Index([('AAPL', 1), ('MSFT', 2), ('META', 3), ('TCS', 4), ('IOCL', 5)], dtype='object')

In [57]:
# it will not work in case of df
# m_df[('AAPL', 1)]


# but in case of df - use this technique
# iloc position based indexing use karta hai.
# [row_position , column_position]
m_df.iloc[0,0]
m_df.iloc[1,0]


# Agar actual index value se access karna ho:
m_df.loc[[('MSFT',2)]]
m_df.loc[[('MSFT',2)]].iloc[0,0]

# iloc → position based
# loc → actual label/index based

np.int64(200)

## actual code of multiindex

In [61]:
# Multiindex

# Multiindex from tuple
t_index = pd.MultiIndex.from_tuples(m_df.index)
t_index

# m_df.loc[('MSFT',2)]


# Multiindex from product
pp_index = [['AAPL','MSFT','META'],[100,200]]
p_index = pd.MultiIndex.from_product(pp_index)
print(p_index)

MultiIndex([('AAPL', 100),
            ('AAPL', 200),
            ('MSFT', 100),
            ('MSFT', 200),
            ('META', 100),
            ('META', 200)],
           )

In [65]:
t_index

MultiIndex([('AAPL', 1),
            ('MSFT', 2),
            ('META', 3),
            ( 'TCS', 4),
            ('IOCL', 5)],
           )

In [ ]:
# check levels in Multiindex
# m_df.index.level[0]
t_index.levels 
t_index.levels[0]
t_index.levels[1]

Index([1, 2, 3, 4, 5], dtype='int64')

In [ ]:
p_index.levels
p_index.levels[0]
p_index.levels[1]

Index([100, 200], dtype='int64')

In [64]:
# creating a serires with multiindex object
pd.Series(index=t_index)
m_ind_ser = pd.Series([100,200,300,400,500],index=t_index)
m_ind_ser
m_ind_ser

AAPL  1    100
MSFT  2    200
META  3    300
TCS   4    400
IOCL  5    500
dtype: int64

In [ ]:
# m_ind_ser['MSFT'] #- give complete output 
# m_ind_ser[('MSFT',2)]   # - it give only value with datatype
m_ind_ser.loc[('MSFT',2)] # - it give only value with datatype

np.int64(200)