## Pivot Tables and Melt functions

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

In [2]:
!pip show ipykernel

Name: ipykernel
Version: 7.3.0
Summary: IPython Kernel for Jupyter
Home-page:
Author:
Author-email: IPython Development Team <ipython-dev@scipy.org>
License:
Location: C:\Users\Dell\Documents\Projects\AI-Agentic-Trading-Bot\venv\Lib\site-packages
Requires: comm, debugpy, ipython, jupyter-client, jupyter-core, matplotlib-inline, nest-asyncio2, packaging, psutil, pyzmq, tornado, traitlets
Required-by: jupyter, jupyter-console, jupyterlab

In [3]:
pd.DataFrame({'AAPL':[100]})
pd.DataFrame({'AAPL':[100],'BTC':[2000],'AAPL':[100],'MSFT':[3000]})

# using melt()  - this wide format data will get converted it into  long format data, cols become rows
pd.DataFrame({'AAPL':[100],'BTC':[2000],'AAPL':[100],'MSFT':[3000]}).melt()

  variable  value
0     AAPL    100
1      BTC   2000
2     MSFT   3000

In [4]:
# rename the col name
pd.DataFrame({'AAPL':[100],'BTC':[2000],'AAPL':[100],'MSFT':[3000]}).melt(var_name='Ticker',value_name='Price')

  Ticker  Price
0   AAPL    100
1    BTC   2000
2   MSFT   3000

In [5]:
pd.DataFrame({
    'Tickers': ['AAPL','BTC','MSFT','META'],
    'Price' : [100,200,300,400],
    'Year' : [2020,2021,2022,2023],
    'Close' : [110,220,320,420]
})

  Tickers  Price  Year  Close
0    AAPL    100  2020    110
1     BTC    200  2021    220
2    MSFT    300  2022    320
3    META    400  2023    420

In [6]:
# it will melt all the cols
pd.DataFrame({
    'Tickers': ['AAPL','BTC','MSFT','META'],
    'Price' : [100,200,300,400],
    'Year' : [2020,2021,2022,2023],
    'Close' : [110,220,320,420]
}).melt()

   variable value
0   Tickers  AAPL
1   Tickers   BTC
2   Tickers  MSFT
3   Tickers  META
4     Price   100
5     Price   200
6     Price   300
7     Price   400
8      Year  2020
9      Year  2021
10     Year  2022
11     Year  2023
12    Close   110
13    Close   220
14    Close   320
15    Close   420

In [7]:
pd.DataFrame({
    'Tickers': ['AAPL','BTC','MSFT','META'],
    'Price' : [100,200,300,400],
    'Year' : [2020,2021,2022,2023],
    'Close' : [110,220,320,420]
}).melt(id_vars=['Tickers'])

   Tickers variable  value
0     AAPL    Price    100
1      BTC    Price    200
2     MSFT    Price    300
3     META    Price    400
4     AAPL     Year   2020
5      BTC     Year   2021
6     MSFT     Year   2022
7     META     Year   2023
8     AAPL    Close    110
9      BTC    Close    220
10    MSFT    Close    320
11    META    Close    420

In [8]:
# change the col name
pd.DataFrame({
    'Tickers': ['AAPL','BTC','MSFT','META'],
    'Price' : [100,200,300,400],
    'Year' : [2020,2021,2022,2023],
    'Close' : [110,220,320,420]
}).melt(id_vars=['Tickers'],var_name='Price',value_name='Value')

   Tickers  Price  Value
0     AAPL  Price    100
1      BTC  Price    200
2     MSFT  Price    300
3     META  Price    400
4     AAPL   Year   2020
5      BTC   Year   2021
6     MSFT   Year   2022
7     META   Year   2023
8     AAPL  Close    110
9      BTC  Close    220
10    MSFT  Close    320
11    META  Close    420

In [ ]:
# melt -> real world example

import pandas as pd
import yfinance as yf

data =  yf.download(tickers=['AAPL','AMZN','MSFT','META'], start= '2024-01-01', end= '2024-06-30',group_by= 'Ticker',auto_adjust=False)
# Future_stack = True -> it removes warning 
# .reset_index()  - by default level 0 index is set - it gives default index
#  but need of level 1 index
data = data.stack(level=0, future_stack=True).reset_index(level=1)
data = data.reset_index()
# data = data.set_index('Date')
melted_df =data.melt(id_vars=['Date','Ticker'], var_name = 'Metrics', value_name = 'Value',value_vars=['Open',	'High',	'Low','Close','Adj Close','Volume'])
melted_df

[*********************100%***********************]  4 of 4 completed

           Date Ticker Metrics         Value
0    2024-01-02   AMZN    Open  1.515400e+02
1    2024-01-02   META    Open  3.513200e+02
2    2024-01-02   MSFT    Open  3.738600e+02
3    2024-01-02   AAPL    Open  1.871500e+02
4    2024-01-03   AMZN    Open  1.492000e+02
...         ...    ...     ...           ...
2971 2024-06-27   AAPL  Volume  4.977270e+07
2972 2024-06-28   AMZN  Volume  7.693020e+07
2973 2024-06-28   META  Volume  1.585510e+07
2974 2024-06-28   MSFT  Volume  2.836230e+07
2975 2024-06-28   AAPL  Volume  8.254270e+07

[2976 rows x 4 columns]

In [14]:
data = data.set_index('Date')

In [15]:
data.columns

Index(['Ticker', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='str', name='Price')

In [16]:
data.index

DatetimeIndex(['2024-01-02', '2024-01-02', '2024-01-02', '2024-01-02',
               '2024-01-03', '2024-01-03', '2024-01-03', '2024-01-03',
               '2024-01-04', '2024-01-04',
               ...
               '2024-06-26', '2024-06-26', '2024-06-27', '2024-06-27',
               '2024-06-27', '2024-06-27', '2024-06-28', '2024-06-28',
               '2024-06-28', '2024-06-28'],
              dtype='datetime64[s]', name='Date', length=496, freq=None)

## Pivot table

In [17]:
data.head()

Price,Ticker,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AMZN,151.539993,152.380005,148.389999,149.929993,149.929993,47339400
2024-01-02,META,351.320007,353.160004,340.010010,346.290009,343.275574,19042200
2024-01-02,MSFT,373.859985,375.899994,366.769989,370.869995,363.801514,25258600
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,183.562195,82488700
2024-01-03,AMZN,149.199997,151.050003,148.330002,148.470001,148.470001,49425500

In [27]:
data.columns

Index(['Ticker', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='str', name='Price')

In [19]:
data.columns.name

'Price'

In [20]:
data.head()

Price,Ticker,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AMZN,151.539993,152.380005,148.389999,149.929993,149.929993,47339400
2024-01-02,META,351.320007,353.160004,340.010010,346.290009,343.275574,19042200
2024-01-02,MSFT,373.859985,375.899994,366.769989,370.869995,363.801514,25258600
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,183.562195,82488700
2024-01-03,AMZN,149.199997,151.050003,148.330002,148.470001,148.470001,49425500

In [21]:
'Price' in data.columns

False

In [ ]:
data

Price,Ticker,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,,
2024-01-02,AMZN,151.539993,152.380005,148.389999,149.929993,149.929993,47339400
2024-01-02,META,351.320007,353.160004,340.010010,346.290009,343.275574,19042200
2024-01-02,MSFT,373.859985,375.899994,366.769989,370.869995,363.801514,25258600
2024-01-02,AAPL,187.149994,188.440002,183.889999,185.639999,183.562195,82488700
2024-01-03,AMZN,149.199997,151.050003,148.330002,148.470001,148.470001,49425500
...,...,...,...,...,...,...,...
2024-06-27,AAPL,214.690002,215.740005,212.350006,214.100006,212.261292,49772700
2024-06-28,AMZN,197.729996,198.850006,192.500000,193.250000,193.250000,76930200
2024-06-28,META,517.150024,521.880005,503.839996,504.220001,500.857819,15855100
2024-06-28,MSFT,453.070007,455.380005,446.410004,446.950012,440.034515,28362300
2024-06-28,AAPL,215.770004,216.070007,210.300003,210.619995,208.811172,82542700

In [26]:
data.columns.name

'Price'

In [29]:
data.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 496 entries, 2024-01-02 to 2024-06-28
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Ticker     496 non-null    str
 1   Open       496 non-null    float64
 2   High       496 non-null    float64
 3   Low        496 non-null    float64
 4   Close      496 non-null    float64
 5   Adj Close  496 non-null    float64
 6   Volume     496 non-null    int64
dtypes: float64(5), int64(1), str(1)
memory usage: 31.0 KB

In [ ]:
data.groupby('Ticker')['Open'].mean()

# return mean of every day of each ticker
data.groupby(['Ticker','Date'])['Open'].mean()

#unstack()  = rows becomes cols  - the same thing can acheive with the pivot table
data.groupby(['Ticker','Date'])['Open'].mean().unstack()

# or
data.pivot_table(index='Ticker',columns='Date', values='Open')
# groupby or pivot_table both gives same result but pivot_table is more efficient

Date,2024-01-02,2024-01-03,2024-01-04,2024-01-05,2024-01-08,2024-01-09,2024-01-10,2024-01-11,2024-01-12,2024-01-16,...,2024-06-14,2024-06-17,2024-06-18,2024-06-20,2024-06-21,2024-06-24,2024-06-25,2024-06-26,2024-06-27,2024-06-28
Ticker,,,,,,,,,,,,,,,,,,,,,
AAPL,187.149994,184.220001,182.149994,181.990005,182.089996,183.919998,184.350006,186.539993,186.059998,182.160004,...,213.850006,213.369995,217.589996,213.929993,210.389999,207.720001,209.149994,211.500000,214.690002,215.770004
AMZN,151.539993,149.199997,145.589996,144.690002,146.740005,148.330002,152.059998,155.039993,155.389999,153.529999,...,183.080002,182.520004,183.740005,182.910004,187.800003,189.330002,186.809998,186.919998,195.009995,197.729996
META,351.320007,344.980011,344.500000,346.989990,354.700012,356.399994,360.170013,372.130005,370.160004,373.649994,...,502.649994,501.670013,504.559998,502.000000,503.450012,499.200012,497.049988,506.649994,514.250000,517.150024
MSFT,373.859985,369.010010,370.670013,368.970001,369.299988,372.010010,376.369995,386.000000,385.489990,393.660004,...,438.279999,442.589996,449.709991,446.299988,447.380005,449.799988,448.250000,449.000000,452.179993,453.070007

In [ ]:
# by default it calulates the mean value
data.pivot_table(index='Ticker',columns='Date', values='Open')
# or
# by default it cal on mean value
# pivot_table applies on - 1 col only i.e  values='Open'
data.pivot_table(index='Ticker',columns='Date', values='Open', aggfunc='mean')

# in short - pivot_table is the advance of groupby

# it applies on all the columns
data.pivot_table(index='Ticker',columns='Date', aggfunc='mean')

Date,2024-01-02,2024-01-03,2024-01-04,2024-01-05,2024-01-08,2024-01-09,2024-01-10,2024-01-11,2024-01-12,2024-01-16,...,2024-06-14,2024-06-17,2024-06-18,2024-06-20,2024-06-21,2024-06-24,2024-06-25,2024-06-26,2024-06-27,2024-06-28
Ticker,,,,,,,,,,,,,,,,,,,,,
AAPL,187.149994,184.220001,182.149994,181.990005,182.089996,183.919998,184.350006,186.539993,186.059998,182.160004,...,213.850006,213.369995,217.589996,213.929993,210.389999,207.720001,209.149994,211.500000,214.690002,215.770004
AMZN,151.539993,149.199997,145.589996,144.690002,146.740005,148.330002,152.059998,155.039993,155.389999,153.529999,...,183.080002,182.520004,183.740005,182.910004,187.800003,189.330002,186.809998,186.919998,195.009995,197.729996
META,351.320007,344.980011,344.500000,346.989990,354.700012,356.399994,360.170013,372.130005,370.160004,373.649994,...,502.649994,501.670013,504.559998,502.000000,503.450012,499.200012,497.049988,506.649994,514.250000,517.150024
MSFT,373.859985,369.010010,370.670013,368.970001,369.299988,372.010010,376.369995,386.000000,385.489990,393.660004,...,438.279999,442.589996,449.709991,446.299988,447.380005,449.799988,448.250000,449.000000,452.179993,453.070007